// A single static theme whose values are CSS custom property references.
// Actual light/dark colors are defined in globals.css via :root and [data-theme="dark"].
// This means styled-components always generates the same class names on server and client,
// eliminating React hydration mismatches caused by theme switching.
export const theme = {
  colors: {
    pageBg: 'var(--color-page-bg)',
    pageText: 'var(--color-page-text)',
    surface: 'var(--color-surface)',
    surfaceHover: 'var(--color-surface-hover)',
    surfaceAlt: 'var(--color-surface-alt)',
    border: 'var(--color-border)',
    borderLight: 'var(--color-border-light)',
    textPrimary: 'var(--color-text-primary)',
    textSecondary: 'var(--color-text-secondary)',
    textMuted: 'var(--color-text-muted)',
    textHint: 'var(--color-text-hint)',
    accent: 'var(--color-accent)',
    accentHover: 'var(--color-accent-hover)',
    accentBg: 'var(--color-accent-bg)',
    accentBorder: 'var(--color-accent-border)',
    navMenuItemHoverBg: 'var(--color-nav-menu-item-hover-bg)',
    inputBorder: 'var(--color-input-border)',
    errorText: 'var(--color-error-text)',
    errorBg: 'var(--color-error-bg)',
    errorBorder: 'var(--color-error-border)',
    successText: 'var(--color-success-text)',
    successBg: 'var(--color-success-bg)',
    successBorder: 'var(--color-success-border)',
    warningText: 'var(--color-warning-text)',
    warningBg: 'var(--color-warning-bg)',
    warningBorder: 'var(--color-warning-border)',
    toastDefaultBorder: 'var(--color-toast-default-border)',
    toastDefaultBg: 'var(--color-toast-default-bg)',
    toastSuccessBorder: 'var(--color-toast-success-border)',
    toastSuccessBg: 'var(--color-toast-success-bg)',
    toastSuccessText: 'var(--color-toast-success-text)',
    toastErrorBorder: 'var(--color-toast-error-border)',
    toastErrorBg: 'var(--color-toast-error-bg)',
    toastErrorText: 'var(--color-toast-error-text)',
    barTrack: 'var(--color-bar-track)',
    barFill: 'var(--color-bar-fill)',
    cancelBg: 'var(--color-cancel-bg)',
    cancelText: 'var(--color-cancel-text)',
    cancelBgHover: 'var(--color-cancel-bg-hover)',
    skeletonBg: 'var(--color-skeleton-bg)',
    skeletonShine: 'var(--color-skeleton-shine)',
    pageButtonDisabledColor: 'var(--color-page-button-disabled)',
  },
}

export type AppTheme = typeof theme
